import React from 'react'

export const metadata = {
    title: 'LearnHub | Blogs',
    description: 'Generated by create next app',
}

const BlogLayout = ({ children }) => {
    return (
        <div>
            {children}
        </div>
    )
}

export default BlogLayout
