import React from 'react'

export const metadata = {
    title: 'LearnHub | Programs',
    description: 'Generated by create next app',
}

const ProgramLayout = ({ children }) => {
    return (
        <div className='font-raleway'>
            {children}
        </div>
    )
}

export default ProgramLayout
