import React from 'react'

export const metadata = {
    title: 'LearnHub | About Us',
    description: 'Generated by create next app',
}

const AboutLayout = ({ children }) => {
    return (
        <div>
            {children}
        </div>
    )
}

export default AboutLayout
