export const metadata=  {
    title : 'Home | Dashboard',
    description: 'Generated by create next app',
}

export default function DashboardLayout({children}){
    return (
        <div>
            {children}
        </div>
    )
}